### ISSUE TITLE
545

### ISSUE THREAD

**Issue by PulsarNeutronStar** [SkippieDippie/RHS-AFRF-Compatibilities#7]
rhs_30Rnd_545x39_7U1_AK
rhs_30Rnd_545x39_7N22_AK
rhs_30Rnd_545x39_7N10_AK
rhs_30Rnd_545x39_AK_plum_green
rhs_30Rnd_545x39_7N6M_plum_AK
rhs_30Rnd_545x39_7N22_plum_AK
rhs_30Rnd_545x39_7N10_plum_AK
rhs_30Rnd_545x39_7N6M_green_AK
rhs_30Rnd_545x39_7N6_green_AK
rhs_30Rnd_545x39_7N22_desert_AK
rhs_30Rnd_545x39_7N10_desert_AK
rhs_30Rnd_545x39_7N22_camo_AK
rhs_30Rnd_545x39_7N10_camo_AK
rhs_60Rnd_545X39_AK_Green
rhs_60Rnd_545X39_7U1_AK
rhs_60Rnd_545X39_7N22_AK
rhs_60Rnd_545X39_7N10_AK
rhs_45Rnd_545X39_AK_Green
rhs_45Rnd_545X39_7U1_AK
rhs_45Rnd_545X39_7N6M_AK
rhs_45Rnd_545X39_7N6_AK
rhs_45Rnd_545X39_7N22_AK
rhs_45Rnd_545X39_7N10_AK
rhs_30Rnd_545x39_7U1_AK
rhs_30Rnd_545x39_7N22_AK
rhs_30Rnd_545x39_7N10_AK
rhs_30Rnd_545x39_AK_plum_green
rhs_30Rnd_545x39_7N6M_plum_AK
rhs_30Rnd_545x39_7N22_plum_AK
rhs_30Rnd_545x39_7N10_plum_AK
rhs_30Rnd_545x39_7N6M_green_AK
rhs_30Rnd_545x39_7N6_green_AK

**Comment by SkippieDippie** [comment]
The compatibility for 5.45x39 has already been implemented. Thus, this issue will be closed.
